//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pizza.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pizza.ServiceReference1.CreditCard))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pizza.ServiceReference1.Product))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pizza.ServiceReference1.Order))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(pizza.ServiceReference1.User))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditCard", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class CreditCard : pizza.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CVVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVV {
            get {
                return this.CVVField;
            }
            set {
                if ((object.ReferenceEquals(this.CVVField, value) != true)) {
                    this.CVVField = value;
                    this.RaisePropertyChanged("CVV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpDate {
            get {
                return this.ExpDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpDateField, value) != true)) {
                    this.ExpDateField = value;
                    this.RaisePropertyChanged("ExpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Product : pizza.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCouponField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCoupon {
            get {
                return this.IsCouponField;
            }
            set {
                if ((this.IsCouponField.Equals(value) != true)) {
                    this.IsCouponField = value;
                    this.RaisePropertyChanged("IsCoupon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Order : pizza.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsApproved {
            get {
                return this.IsApprovedField;
            }
            set {
                if ((this.IsApprovedField.Equals(value) != true)) {
                    this.IsApprovedField = value;
                    this.RaisePropertyChanged("IsApproved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderLevel {
            get {
                return this.OrderLevelField;
            }
            set {
                if ((this.OrderLevelField.Equals(value) != true)) {
                    this.OrderLevelField = value;
                    this.RaisePropertyChanged("OrderLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class User : pizza.ServiceReference1.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bday {
            get {
                return this.BdayField;
            }
            set {
                if ((object.ReferenceEquals(this.BdayField, value) != true)) {
                    this.BdayField = value;
                    this.RaisePropertyChanged("Bday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FName {
            get {
                return this.FNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FNameField, value) != true)) {
                    this.FNameField = value;
                    this.RaisePropertyChanged("FName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LName {
            get {
                return this.LNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LNameField, value) != true)) {
                    this.LNameField = value;
                    this.RaisePropertyChanged("LName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItemSummary", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class OrderItemSummary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPizzaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSummaryRowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal LineTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PizzaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaleTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPizza {
            get {
                return this.IsPizzaField;
            }
            set {
                if ((this.IsPizzaField.Equals(value) != true)) {
                    this.IsPizzaField = value;
                    this.RaisePropertyChanged("IsPizza");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSummaryRow {
            get {
                return this.IsSummaryRowField;
            }
            set {
                if ((this.IsSummaryRowField.Equals(value) != true)) {
                    this.IsSummaryRowField = value;
                    this.RaisePropertyChanged("IsSummaryRow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LineTotal {
            get {
                return this.LineTotalField;
            }
            set {
                if ((this.LineTotalField.Equals(value) != true)) {
                    this.LineTotalField = value;
                    this.RaisePropertyChanged("LineTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PizzaId {
            get {
                return this.PizzaIdField;
            }
            set {
                if ((this.PizzaIdField.Equals(value) != true)) {
                    this.PizzaIdField = value;
                    this.RaisePropertyChanged("PizzaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaleText {
            get {
                return this.SaleTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SaleTextField, value) != true)) {
                    this.SaleTextField = value;
                    this.RaisePropertyChanged("SaleText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PizzaSlice", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class PizzaSlice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AnchoviField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GreenPepperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool KabanosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OlivesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OnionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PepperoniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PineappleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PizzaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SliceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TunaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Anchovi {
            get {
                return this.AnchoviField;
            }
            set {
                if ((this.AnchoviField.Equals(value) != true)) {
                    this.AnchoviField = value;
                    this.RaisePropertyChanged("Anchovi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GreenPepper {
            get {
                return this.GreenPepperField;
            }
            set {
                if ((this.GreenPepperField.Equals(value) != true)) {
                    this.GreenPepperField = value;
                    this.RaisePropertyChanged("GreenPepper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Kabanos {
            get {
                return this.KabanosField;
            }
            set {
                if ((this.KabanosField.Equals(value) != true)) {
                    this.KabanosField = value;
                    this.RaisePropertyChanged("Kabanos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Olives {
            get {
                return this.OlivesField;
            }
            set {
                if ((this.OlivesField.Equals(value) != true)) {
                    this.OlivesField = value;
                    this.RaisePropertyChanged("Olives");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Onion {
            get {
                return this.OnionField;
            }
            set {
                if ((this.OnionField.Equals(value) != true)) {
                    this.OnionField = value;
                    this.RaisePropertyChanged("Onion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pepperoni {
            get {
                return this.PepperoniField;
            }
            set {
                if ((this.PepperoniField.Equals(value) != true)) {
                    this.PepperoniField = value;
                    this.RaisePropertyChanged("Pepperoni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Pineapple {
            get {
                return this.PineappleField;
            }
            set {
                if ((this.PineappleField.Equals(value) != true)) {
                    this.PineappleField = value;
                    this.RaisePropertyChanged("Pineapple");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PizzaId {
            get {
                return this.PizzaIdField;
            }
            set {
                if ((this.PizzaIdField.Equals(value) != true)) {
                    this.PizzaIdField = value;
                    this.RaisePropertyChanged("PizzaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SliceNumber {
            get {
                return this.SliceNumberField;
            }
            set {
                if ((this.SliceNumberField.Equals(value) != true)) {
                    this.SliceNumberField = value;
                    this.RaisePropertyChanged("SliceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Tuna {
            get {
                return this.TunaField;
            }
            set {
                if ((this.TunaField.Equals(value) != true)) {
                    this.TunaField = value;
                    this.RaisePropertyChanged("Tuna");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        void DeleteUser(pizza.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUser", ReplyAction="http://tempuri.org/IService1/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(pizza.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        void AddUser(pizza.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        System.Threading.Tasks.Task AddUserAsync(pizza.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        void UpdateUser(pizza.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUser", ReplyAction="http://tempuri.org/IService1/UpdateUserResponse")]
        System.Threading.Tasks.Task UpdateUserAsync(pizza.ServiceReference1.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsersList", ReplyAction="http://tempuri.org/IService1/GetUsersListResponse")]
        pizza.ServiceReference1.User[] GetUsersList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsersList", ReplyAction="http://tempuri.org/IService1/GetUsersListResponse")]
        System.Threading.Tasks.Task<pizza.ServiceReference1.User[]> GetUsersListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByEmail", ReplyAction="http://tempuri.org/IService1/GetUserByEmailResponse")]
        pizza.ServiceReference1.User GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserByEmail", ReplyAction="http://tempuri.org/IService1/GetUserByEmailResponse")]
        System.Threading.Tasks.Task<pizza.ServiceReference1.User> GetUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveCard", ReplyAction="http://tempuri.org/IService1/SaveCardResponse")]
        void SaveCard(pizza.ServiceReference1.CreditCard card);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveCard", ReplyAction="http://tempuri.org/IService1/SaveCardResponse")]
        System.Threading.Tasks.Task SaveCardAsync(pizza.ServiceReference1.CreditCard card);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        void AddProduct(pizza.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProduct", ReplyAction="http://tempuri.org/IService1/AddProductResponse")]
        System.Threading.Tasks.Task AddProductAsync(pizza.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductsList", ReplyAction="http://tempuri.org/IService1/GetProductsListResponse")]
        pizza.ServiceReference1.Product[] GetProductsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductsList", ReplyAction="http://tempuri.org/IService1/GetProductsListResponse")]
        System.Threading.Tasks.Task<pizza.ServiceReference1.Product[]> GetProductsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProduct", ReplyAction="http://tempuri.org/IService1/UpdateProductResponse")]
        void UpdateProduct(pizza.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProduct", ReplyAction="http://tempuri.org/IService1/UpdateProductResponse")]
        System.Threading.Tasks.Task UpdateProductAsync(pizza.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        void DeleteProduct(pizza.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteProduct", ReplyAction="http://tempuri.org/IService1/DeleteProductResponse")]
        System.Threading.Tasks.Task DeleteProductAsync(pizza.ServiceReference1.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrder", ReplyAction="http://tempuri.org/IService1/AddOrderResponse")]
        void AddOrder(pizza.ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrder", ReplyAction="http://tempuri.org/IService1/AddOrderResponse")]
        System.Threading.Tasks.Task AddOrderAsync(pizza.ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOrder", ReplyAction="http://tempuri.org/IService1/UpdateOrderResponse")]
        void UpdateOrder(pizza.ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOrder", ReplyAction="http://tempuri.org/IService1/UpdateOrderResponse")]
        System.Threading.Tasks.Task UpdateOrderAsync(pizza.ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        void DeleteOrder(pizza.ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        System.Threading.Tasks.Task DeleteOrderAsync(pizza.ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrdersList", ReplyAction="http://tempuri.org/IService1/GetOrdersListResponse")]
        pizza.ServiceReference1.Order[] GetOrdersList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrdersList", ReplyAction="http://tempuri.org/IService1/GetOrdersListResponse")]
        System.Threading.Tasks.Task<pizza.ServiceReference1.Order[]> GetOrdersListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderItemsSummary", ReplyAction="http://tempuri.org/IService1/GetOrderItemsSummaryResponse")]
        pizza.ServiceReference1.OrderItemSummary[] GetOrderItemsSummary(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOrderItemsSummary", ReplyAction="http://tempuri.org/IService1/GetOrderItemsSummaryResponse")]
        System.Threading.Tasks.Task<pizza.ServiceReference1.OrderItemSummary[]> GetOrderItemsSummaryAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProductToCurrentOrder", ReplyAction="http://tempuri.org/IService1/AddProductToCurrentOrderResponse")]
        int AddProductToCurrentOrder(int userId, string address, string productName, string category, decimal price, string picture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProductToCurrentOrder", ReplyAction="http://tempuri.org/IService1/AddProductToCurrentOrderResponse")]
        System.Threading.Tasks.Task<int> AddProductToCurrentOrderAsync(int userId, string address, string productName, string category, decimal price, string picture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPizzaToCurrentOrder", ReplyAction="http://tempuri.org/IService1/AddPizzaToCurrentOrderResponse")]
        int AddPizzaToCurrentOrder(int userId, string address, pizza.ServiceReference1.PizzaSlice[] slices);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPizzaToCurrentOrder", ReplyAction="http://tempuri.org/IService1/AddPizzaToCurrentOrderResponse")]
        System.Threading.Tasks.Task<int> AddPizzaToCurrentOrderAsync(int userId, string address, pizza.ServiceReference1.PizzaSlice[] slices);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOpenOrderForUser", ReplyAction="http://tempuri.org/IService1/GetOpenOrderForUserResponse")]
        pizza.ServiceReference1.Order GetOpenOrderForUser(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetOpenOrderForUser", ReplyAction="http://tempuri.org/IService1/GetOpenOrderForUserResponse")]
        System.Threading.Tasks.Task<pizza.ServiceReference1.Order> GetOpenOrderForUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IncreasePizzaQuantity", ReplyAction="http://tempuri.org/IService1/IncreasePizzaQuantityResponse")]
        void IncreasePizzaQuantity(int pizzaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IncreasePizzaQuantity", ReplyAction="http://tempuri.org/IService1/IncreasePizzaQuantityResponse")]
        System.Threading.Tasks.Task IncreasePizzaQuantityAsync(int pizzaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IncreaseProductQuantity", ReplyAction="http://tempuri.org/IService1/IncreaseProductQuantityResponse")]
        void IncreaseProductQuantity(int orderId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IncreaseProductQuantity", ReplyAction="http://tempuri.org/IService1/IncreaseProductQuantityResponse")]
        System.Threading.Tasks.Task IncreaseProductQuantityAsync(int orderId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DecreasePizzaQuantity", ReplyAction="http://tempuri.org/IService1/DecreasePizzaQuantityResponse")]
        void DecreasePizzaQuantity(int pizzaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DecreasePizzaQuantity", ReplyAction="http://tempuri.org/IService1/DecreasePizzaQuantityResponse")]
        System.Threading.Tasks.Task DecreasePizzaQuantityAsync(int pizzaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DecreaseProductQuantity", ReplyAction="http://tempuri.org/IService1/DecreaseProductQuantityResponse")]
        void DecreaseProductQuantity(int orderId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DecreaseProductQuantity", ReplyAction="http://tempuri.org/IService1/DecreaseProductQuantityResponse")]
        System.Threading.Tasks.Task DecreaseProductQuantityAsync(int orderId, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HasSavedCard", ReplyAction="http://tempuri.org/IService1/HasSavedCardResponse")]
        bool HasSavedCard(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HasSavedCard", ReplyAction="http://tempuri.org/IService1/HasSavedCardResponse")]
        System.Threading.Tasks.Task<bool> HasSavedCardAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOrderLevel", ReplyAction="http://tempuri.org/IService1/UpdateOrderLevelResponse")]
        void UpdateOrderLevel(int orderId, int orderLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOrderLevel", ReplyAction="http://tempuri.org/IService1/UpdateOrderLevelResponse")]
        System.Threading.Tasks.Task UpdateOrderLevelAsync(int orderId, int orderLevel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : pizza.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<pizza.ServiceReference1.IService1>, pizza.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public void DeleteUser(pizza.ServiceReference1.User user) {
            base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(pizza.ServiceReference1.User user) {
            return base.Channel.DeleteUserAsync(user);
        }
        
        public void AddUser(pizza.ServiceReference1.User user) {
            base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task AddUserAsync(pizza.ServiceReference1.User user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public void UpdateUser(pizza.ServiceReference1.User user) {
            base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task UpdateUserAsync(pizza.ServiceReference1.User user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public pizza.ServiceReference1.User[] GetUsersList() {
            return base.Channel.GetUsersList();
        }
        
        public System.Threading.Tasks.Task<pizza.ServiceReference1.User[]> GetUsersListAsync() {
            return base.Channel.GetUsersListAsync();
        }
        
        public pizza.ServiceReference1.User GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<pizza.ServiceReference1.User> GetUserByEmailAsync(string email) {
            return base.Channel.GetUserByEmailAsync(email);
        }
        
        public void SaveCard(pizza.ServiceReference1.CreditCard card) {
            base.Channel.SaveCard(card);
        }
        
        public System.Threading.Tasks.Task SaveCardAsync(pizza.ServiceReference1.CreditCard card) {
            return base.Channel.SaveCardAsync(card);
        }
        
        public void AddProduct(pizza.ServiceReference1.Product product) {
            base.Channel.AddProduct(product);
        }
        
        public System.Threading.Tasks.Task AddProductAsync(pizza.ServiceReference1.Product product) {
            return base.Channel.AddProductAsync(product);
        }
        
        public pizza.ServiceReference1.Product[] GetProductsList() {
            return base.Channel.GetProductsList();
        }
        
        public System.Threading.Tasks.Task<pizza.ServiceReference1.Product[]> GetProductsListAsync() {
            return base.Channel.GetProductsListAsync();
        }
        
        public void UpdateProduct(pizza.ServiceReference1.Product product) {
            base.Channel.UpdateProduct(product);
        }
        
        public System.Threading.Tasks.Task UpdateProductAsync(pizza.ServiceReference1.Product product) {
            return base.Channel.UpdateProductAsync(product);
        }
        
        public void DeleteProduct(pizza.ServiceReference1.Product product) {
            base.Channel.DeleteProduct(product);
        }
        
        public System.Threading.Tasks.Task DeleteProductAsync(pizza.ServiceReference1.Product product) {
            return base.Channel.DeleteProductAsync(product);
        }
        
        public void AddOrder(pizza.ServiceReference1.Order order) {
            base.Channel.AddOrder(order);
        }
        
        public System.Threading.Tasks.Task AddOrderAsync(pizza.ServiceReference1.Order order) {
            return base.Channel.AddOrderAsync(order);
        }
        
        public void UpdateOrder(pizza.ServiceReference1.Order order) {
            base.Channel.UpdateOrder(order);
        }
        
        public System.Threading.Tasks.Task UpdateOrderAsync(pizza.ServiceReference1.Order order) {
            return base.Channel.UpdateOrderAsync(order);
        }
        
        public void DeleteOrder(pizza.ServiceReference1.Order order) {
            base.Channel.DeleteOrder(order);
        }
        
        public System.Threading.Tasks.Task DeleteOrderAsync(pizza.ServiceReference1.Order order) {
            return base.Channel.DeleteOrderAsync(order);
        }
        
        public pizza.ServiceReference1.Order[] GetOrdersList() {
            return base.Channel.GetOrdersList();
        }
        
        public System.Threading.Tasks.Task<pizza.ServiceReference1.Order[]> GetOrdersListAsync() {
            return base.Channel.GetOrdersListAsync();
        }
        
        public pizza.ServiceReference1.OrderItemSummary[] GetOrderItemsSummary(int orderId) {
            return base.Channel.GetOrderItemsSummary(orderId);
        }
        
        public System.Threading.Tasks.Task<pizza.ServiceReference1.OrderItemSummary[]> GetOrderItemsSummaryAsync(int orderId) {
            return base.Channel.GetOrderItemsSummaryAsync(orderId);
        }
        
        public int AddProductToCurrentOrder(int userId, string address, string productName, string category, decimal price, string picture) {
            return base.Channel.AddProductToCurrentOrder(userId, address, productName, category, price, picture);
        }
        
        public System.Threading.Tasks.Task<int> AddProductToCurrentOrderAsync(int userId, string address, string productName, string category, decimal price, string picture) {
            return base.Channel.AddProductToCurrentOrderAsync(userId, address, productName, category, price, picture);
        }
        
        public int AddPizzaToCurrentOrder(int userId, string address, pizza.ServiceReference1.PizzaSlice[] slices) {
            return base.Channel.AddPizzaToCurrentOrder(userId, address, slices);
        }
        
        public System.Threading.Tasks.Task<int> AddPizzaToCurrentOrderAsync(int userId, string address, pizza.ServiceReference1.PizzaSlice[] slices) {
            return base.Channel.AddPizzaToCurrentOrderAsync(userId, address, slices);
        }
        
        public pizza.ServiceReference1.Order GetOpenOrderForUser(int userId) {
            return base.Channel.GetOpenOrderForUser(userId);
        }
        
        public System.Threading.Tasks.Task<pizza.ServiceReference1.Order> GetOpenOrderForUserAsync(int userId) {
            return base.Channel.GetOpenOrderForUserAsync(userId);
        }
        
        public void IncreasePizzaQuantity(int pizzaId) {
            base.Channel.IncreasePizzaQuantity(pizzaId);
        }
        
        public System.Threading.Tasks.Task IncreasePizzaQuantityAsync(int pizzaId) {
            return base.Channel.IncreasePizzaQuantityAsync(pizzaId);
        }
        
        public void IncreaseProductQuantity(int orderId, int productId) {
            base.Channel.IncreaseProductQuantity(orderId, productId);
        }
        
        public System.Threading.Tasks.Task IncreaseProductQuantityAsync(int orderId, int productId) {
            return base.Channel.IncreaseProductQuantityAsync(orderId, productId);
        }
        
        public void DecreasePizzaQuantity(int pizzaId) {
            base.Channel.DecreasePizzaQuantity(pizzaId);
        }
        
        public System.Threading.Tasks.Task DecreasePizzaQuantityAsync(int pizzaId) {
            return base.Channel.DecreasePizzaQuantityAsync(pizzaId);
        }
        
        public void DecreaseProductQuantity(int orderId, int productId) {
            base.Channel.DecreaseProductQuantity(orderId, productId);
        }
        
        public System.Threading.Tasks.Task DecreaseProductQuantityAsync(int orderId, int productId) {
            return base.Channel.DecreaseProductQuantityAsync(orderId, productId);
        }
        
        public bool HasSavedCard(int userId) {
            return base.Channel.HasSavedCard(userId);
        }
        
        public System.Threading.Tasks.Task<bool> HasSavedCardAsync(int userId) {
            return base.Channel.HasSavedCardAsync(userId);
        }
        
        public void UpdateOrderLevel(int orderId, int orderLevel) {
            base.Channel.UpdateOrderLevel(orderId, orderLevel);
        }
        
        public System.Threading.Tasks.Task UpdateOrderLevelAsync(int orderId, int orderLevel) {
            return base.Channel.UpdateOrderLevelAsync(orderId, orderLevel);
        }
    }
}
